name: Deploy to Production
on:
  push:
    branches:
      - Production
  pull_request_review:
    types:
      - submitted

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
              
      - name: Build, Tag and Push Docker Image to AWS ECR
        env:
            ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
            IMAGE_NAME: my-app
            TAG: ${{ github.sha }}
        run: |
            docker build -t $ECR_REGISTRY/$IMAGE_NAME:$TAG .
            docker push $ECR_REGISTRY/$IMAGE_NAME:$TAG

      - name: Deploy to Fargate
        env:
          AWS_REGION: us-east-1 
          SERVICE_STACK_NAME: my-app-service-stack
          TASK_DEFINITION_FILE: task_definition.yml
          SERVICE_DEFINITION_FILE: service_definition.yml
        run: |
          aws cloudformation deploy \
            --region $AWS_REGION \
            --stack-name $SERVICE_STACK_NAME \
            --template-file template.yml \
            --parameter-overrides \
              TaskDefinitionFile=$TASK_DEFINITION_FILE \
              ServiceDefinitionFile=$SERVICE_DEFINITION_FILE \
            --capabilities CAPABILITY_NAMED_IAM
